# Generated by Django 5.0.3 on 2024-03-09 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pokemons', '0002_rename_pokedex_id_pokemon_pokedexid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='nomeDoPokemon',
            new_name='nomePokemon',
        ),
    ]
