# Generated by Django 5.0.3 on 2024-03-09 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pokemons', '0003_rename_nomedopokemon_pokemon_nomepokemon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='habilidade',
        ),
    ]
