# Generated by Django 5.0.3 on 2024-03-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pokemons', '0004_remove_pokemon_habilidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='habilidade',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Habilidades'),
        ),
    ]
