# Generated by Django 5.0.3 on 2024-03-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pokemons', '0005_pokemon_habilidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='tipagem',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Tipagem'),
        ),
    ]
